version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: example_dev_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=example_dev
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
